### ISSUE TITLE
Astra Camera

### ISSUE THREAD

**Issue by sujaymanb** [CSUHuman-UAV-UGV-Collaboration/Bots-Repo#1]
The launch file for astra camera is not working.  Lets compare with the netbooks from the turtlebots and the notes that the professor sent in the email.

**Comment by heeterwill** [comment]
Resolved. Follow these instructions:

--------------------------

Create a file with the following contents and name it "orbbec-usb.rules" 

SUBSYSTEM=="usb", ATTR{idProduct}=="0401", ATTR{idVendor}=="2bc5", MODE:="0666", OWNER:="root", GROUP:="video"
SUBSYSTEM=="usb", ATTR{idProduct}=="0402", ATTR{idVendor}=="2bc5", MODE:="0666", OWNER:="root", GROUP:="video"
SUBSYSTEM=="usb", ATTR{idProduct}=="0403", ATTR{idVendor}=="2bc5", MODE:="0666", OWNER:="root", GROUP:="video"
SUBSYSTEM=="usb", ATTR{idProduct}=="0404", ATTR{idVendor}=="2bc5", MODE:="0666", OWNER:="root", GROUP:="video"
SUBSYSTEM=="usb", ATTR{idProduct}=="0405", ATTR{idVendor}=="2bc5", MODE:="0666", OWNER:="root", GROUP:="video"

---------------------------

then run this command in terminal:

sudo cp orbbec-usb.rules /etc/udev/rules.d/

---------------------------

to activate it after connecting the camera, run this command:

udevadm control --reload-rules

---------------------------

That should get it working.
Note: If you are using a different model Orbbec Astra camera, you may need to modify the file.
